import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { HydratedDocument } from "mongoose";

export type EmrTemplateDocument = HydratedDocument<EmrTemplate>;

/** Singleton document – always queried by key = "default" */
@Schema({ timestamps: true, collection: "emr_templates" })
export class EmrTemplate {
  @Prop({ type: String, default: "default", unique: true })
  key!: string;

  /** Full tab/section/field configuration – stored as flexible JSON */
  @Prop({ type: Object, default: () => ({ tabs: [] }) })
  config!: Record<string, any>;
}

export const EmrTemplateSchema = SchemaFactory.createForClass(EmrTemplate);

/* ─── Physical Exam tab (Биеийн үзлэг) ────────────────────────────── */
export const PHYSICAL_EXAM_TAB = {
  id: "tab_physical_exam",
  name: "Биеийн үзлэг",
  order: 1,
  sections: [
    {
      id: "sec_pe_vitals",
      name: "Амин үзүүлэлт",
      order: 0,
      type: "custom",
      fields: [
        {
          id: "f_pe_general_condition",
          label: "Биеийн ерөнхий байдал",
          type: "select",
          options: ["Хэвийн", "Дунд зэргийн хүнд", "Хүнд", "Маш хүнд"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_height",
          label: "Өндөр",
          type: "number",
          options: [],
          required: false,
          unit: "см",
          placeholder: "170",
        },
        {
          id: "f_pe_weight",
          label: "Биеийн жин",
          type: "number",
          options: [],
          required: false,
          unit: "кг",
          placeholder: "70",
        },
        {
          id: "f_pe_bp_systolic",
          label: "Артерийн дээд даралт",
          type: "number",
          options: [],
          required: false,
          unit: "ммМУ",
          placeholder: "120",
        },
        {
          id: "f_pe_bp_diastolic",
          label: "Артерийн доод даралт",
          type: "number",
          options: [],
          required: false,
          unit: "ммМУ",
          placeholder: "80",
        },
        {
          id: "f_pe_pulse",
          label: "Пульс",
          type: "number",
          options: [],
          required: false,
          unit: "/мин",
          placeholder: "72",
        },
        {
          id: "f_pe_spo2",
          label: "Сатураци",
          type: "number",
          options: [],
          required: false,
          unit: "%",
          placeholder: "98",
        },
        {
          id: "f_pe_rr",
          label: "Амьсгалын тоо",
          type: "number",
          options: [],
          required: false,
          unit: "/мин",
          placeholder: "16",
        },
        {
          id: "f_pe_temp",
          label: "Биеийн температур",
          type: "number",
          options: [],
          required: false,
          unit: "°C",
          placeholder: "36.6",
        },
      ],
    },
    {
      id: "sec_pe_skin",
      name: "Арьс, салстын байдал",
      order: 1,
      type: "custom",
      fields: [
        {
          id: "f_pe_skin_color",
          label: "Арьс салстын өнгө",
          type: "radio",
          options: ["Хэвийн", "Цайвар", "Шарлалттай", "Хөхрөлттэй", "Улайлттай"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_cyanosis",
          label: "Хөхрөлт",
          type: "radio",
          options: ["Байхгүй", "Захын", "Төвийн", "Нийт"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_skin_moisture",
          label: "Арьс салст чийглэг эсэх",
          type: "radio",
          options: ["Хэвийн", "Хуурай", "Чийглэг", "Хэт чийглэг"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_skin_lesion",
          label: "Арьсан дээрх эмгэг",
          type: "radio",
          options: ["Байхгүй", "Spider angioma", "Palmar erythema", "Петехи", "Гематома", "Шарх", "Бусад"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_lesion_location",
          label: "Эмгэгийн байршил",
          type: "radio",
          options: ["Нүүр", "Мөр", "Гар", "Их бие", "Хонгил", "Хөл", "Нийтлэг"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_lesion_feature",
          label: "Эмгэгийн онцлог",
          type: "radio",
          options: ["Тэгш хуваарилалттай", "Нэг талын", "Хоёр талын", "Голт", "Захын"],
          required: false,
          unit: "",
          placeholder: "",
        },
      ],
    },
    {
      id: "sec_pe_edema_joints",
      name: "Хаван, Үе мөч",
      order: 2,
      type: "custom",
      fields: [
        {
          id: "f_pe_edema_present",
          label: "Хавантай эсэх",
          type: "radio",
          options: ["Байхгүй", "Хавантай"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_edema_desc",
          label: "Хаван тодорхойлолт",
          type: "radio",
          options: ["Доод мөч", "Нүүр", "Их бие", "Нэг талын", "Хоёр талын", "Нурдуу", "Хатуу"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_joint",
          label: "Үе мөчний хэлбэр",
          type: "radio",
          options: ["Хэвийн", "Өрчилгөдсөн", "Хавдсан", "Шингэн хуримтлалтай", "Деформац"],
          required: false,
          unit: "",
          placeholder: "",
        },
      ],
    },
    {
      id: "sec_pe_liver",
      name: "Элэгний эмгэгийн шинж",
      order: 3,
      type: "custom",
      fields: [
        {
          id: "f_pe_liver_signs",
          label: "Элэгний эмгэгийн шинж",
          type: "checkbox",
          options: ["Spider angioma", "Palmar erythema", "Caput medusae", "Гинекомастия", "Leuconychia", "Байхгүй"],
          required: false,
          unit: "",
          placeholder: "",
        },
      ],
    },
    {
      id: "sec_pe_encephalopathy",
      name: "Энцефалопати",
      order: 4,
      type: "custom",
      fields: [
        {
          id: "f_pe_enceph_cause",
          label: "Энцефалопатийн суурь шалтгаан",
          type: "radio",
          options: ["Архины", "Вирусын гепатит", "NAFLD", "Автоиммун", "PBC", "Вильсон", "Бусад"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_west_haven",
          label: "West Haven criteria",
          type: "radio",
          options: [
            "0 – Хэвийн (субклиник өөрчлөлтгүй)",
            "I – Анхаарал суларсан, нойрмог, сэтгэл хөдлөлийн өөрчлөлт",
            "II – Дезориентаци, байнгын нойрмог, хэл яриа алдагдсан",
            "III – Ухаан алдсан, командны дагуу хариу үйлдэл хийдэг",
            "IV – Гүн кома, өдөөлтөд хариу байхгүй",
          ],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_enceph_course",
          label: "Энцефалопатийн явц",
          type: "radio",
          options: ["Цочмог", "Архаг", "Цочмог дэхийлтэй", "Давтагдах"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_enceph_trigger",
          label: "Нөхцөлдүүлэгч хүчин зүйл",
          type: "checkbox",
          options: [
            "Халдвар",
            "ГИ цус алдалт",
            "Констипаци",
            "Электролит тэнцвэр алдагдсан",
            "Диуретик хэрэглээ",
            "Белок ихэссэн хоол",
            "Мэс засал",
            "Бусад",
          ],
          required: false,
          unit: "",
          placeholder: "",
        },
      ],
    },
    {
      id: "sec_pe_urine_weight",
      name: "Шээс, Жингийн өөрчлөлт",
      order: 5,
      type: "custom",
      fields: [
        {
          id: "f_pe_urine_output",
          label: "Хоногийн шээсний гарц",
          type: "radio",
          options: ["<500 мл (олигури)", "500–1000 мл (бага)", "1000–2000 мл (хэвийн)", ">2000 мл (полиури)"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_urine_color",
          label: "Шээсний өнгө",
          type: "radio",
          options: ["Цайвар шар", "Шар", "Хүрэн шар", "Хүрэн", "Улаан", "Хөөсрөлттэй"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_nocturia",
          label: "Шөнө шээдэг эсэх",
          type: "radio",
          options: ["Байхгүй", "Тийм – 1-2 удаа", "Тийм – 3+ удаа"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_weight_loss",
          label: "Жингийн алдагдал",
          type: "radio",
          options: ["Байхгүй", "<5%", "5–10%", ">10%"],
          required: false,
          unit: "",
          placeholder: "",
        },
        {
          id: "f_pe_weight_loss_attempt",
          label: "Жин хасах оролдлого",
          type: "radio",
          options: ["Тийм", "Үгүй"],
          required: false,
          unit: "",
          placeholder: "",
        },
      ],
    },
  ],
};

/* ─── Default template config ──────────────────────────────────────── */
export const DEFAULT_TEMPLATE_CONFIG = {
  tabs: [
    {
      id: "tab_detail",
      name: "Дэлгэрэнгүй тэмдэглэл",
      order: 0,
      sections: [
        {
          id: "sec_vitals",
          name: "Амин үзүүлэлт",
          order: 0,
          type: "vitals",
          fields: [],
        },
        {
          id: "sec_general",
          name: "Ерөнхий үзлэг",
          order: 1,
          type: "custom",
          fields: [
            {
              id: "f_general_condition",
              label: "Биеийн ерөнхий байдал",
              type: "select",
              options: ["Хөнгөн", "Дунд", "Хүнд", "Маш хүнд", "Үхлүүт"],
              required: false,
              unit: "",
              placeholder: "",
            },
          ],
        },
        {
          id: "sec_head_eye",
          name: "Толгой, нүдний үзлэг",
          order: 2,
          type: "custom",
          fields: [],
        },
        {
          id: "sec_ent",
          name: "Хамар, хоолой, чихний үзлэг",
          order: 3,
          type: "custom",
          fields: [],
        },
        {
          id: "sec_chest",
          name: "Цээжний үзлэг",
          order: 4,
          type: "custom",
          fields: [],
        },
        {
          id: "sec_abdomen",
          name: "Хэвлийн үзлэг",
          order: 5,
          type: "custom",
          fields: [],
        },
        {
          id: "sec_urogenital",
          name: "Дав, цавь, бэлгийн эрхтний үзлэг",
          order: 6,
          type: "custom",
          fields: [],
        },
        {
          id: "sec_msk",
          name: "Тулгуур эрхтэн, мөчдийн үзлэг",
          order: 7,
          type: "custom",
          fields: [],
        },
        {
          id: "sec_neuro",
          name: "Неврологийн үзлэг",
          order: 8,
          type: "custom",
          fields: [],
        },
      ],
    },
    PHYSICAL_EXAM_TAB,
  ],
};
